# Generated by Django 4.1.5 on 2023-11-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenedLink', '0002_linkhit_alter_shortenedlink_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedlink',
            name='hit_count',
        ),
        migrations.DeleteModel(
            name='LinkHit',
        ),
    ]
