# Generated by Django 4.1.5 on 2023-11-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenedLink', '0004_linkhit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkHit',
        ),
    ]
